# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['backend/core/main.py'],
    pathex=['.'],  # Добавляем корень проекта в путь поиска
    binaries=[],
    datas=[
        ('migrations', 'migrations'),
        ('alembic.ini', '.'),
        ('config', 'config'),
        ('docs/docx-templates', 'docs/docx-templates'),
    ],
    hiddenimports=[
        # Uvicorn modules
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        # Auth and database
        'passlib.handlers.bcrypt',
        'sqlalchemy.sql.default_comparator',
        'psycopg',
        'psycopg2',
        'alembic.operations',
        'docxtpl',
        # Backend modules
        'backend',
        'backend.core',
        'backend.core.main',
        'backend.core.config',
        'backend.core.database',
        'backend.core.logging_config',
        'backend.app',
        'backend.app.models',
        'backend.app.schemas',
        'backend.routes',
        'backend.routes.main_table',
        'backend.routes.files',
        'backend.routes.archive',
        'backend.routes.auth',
        'backend.routes.pinned_documents',
        'backend.routes.backup',
        'backend.routes.health',
        'backend.routes.contracts',
        'backend.routes.documents',
        'backend.services',
        'backend.services.main_table',
        'backend.services.archive',
        'backend.services.backup',
        'backend.services.documents',
        'backend.middleware',
        'backend.middleware.logging_middleware',
        'backend.utils',
        'backend.utils.auth',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy.tests',
        'scipy',
        'pytest',
        'IPython',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='deltica-server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
