"""add is_active_certificate to equipment_files

Revision ID: 1418f8d1f00e
Revises: fbb1be5e8a29
Create Date: 2026-01-17 14:36:19.940078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1418f8d1f00e'
down_revision: Union[str, Sequence[str], None] = 'fbb1be5e8a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_files', sa.Column('is_active_certificate', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_files', 'is_active_certificate')
    # ### end Alembic commands ###
