"""Add pinned_documents table

Revision ID: 3022ff928dd6
Revises: 0eda230e7a45
Create Date: 2025-10-17 18:29:00.045815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3022ff928dd6'
down_revision: Union[str, Sequence[str], None] = '0eda230e7a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinned_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pinned_documents'))
    )
    op.create_index(op.f('ix_pinned_documents_id'), 'pinned_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pinned_documents_id'), table_name='pinned_documents')
    op.drop_table('pinned_documents')
    # ### end Alembic commands ###
