"""Add budget_item and code_rate to finance tables

Revision ID: b0bd63c0bacb
Revises: f7e0dadf8ae2
Create Date: 2025-10-20 19:52:03.079828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0bd63c0bacb'
down_revision: Union[str, Sequence[str], None] = 'f7e0dadf8ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем budget_item как nullable сначала
    op.add_column('archived_finance', sa.Column('budget_item', sa.String(), nullable=True))
    op.add_column('archived_finance', sa.Column('code_rate', sa.String(), nullable=True))
    op.add_column('finance', sa.Column('budget_item', sa.String(), nullable=True))
    op.add_column('finance', sa.Column('code_rate', sa.String(), nullable=True))

    # Заполняем существующие записи дефолтным значением
    op.execute("UPDATE finance SET budget_item = '00.00.00.0' WHERE budget_item IS NULL")
    op.execute("UPDATE archived_finance SET budget_item = '00.00.00.0' WHERE budget_item IS NULL")

    # Теперь делаем budget_item NOT NULL
    op.alter_column('finance', 'budget_item', nullable=False)
    op.alter_column('archived_finance', 'budget_item', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finance', 'code_rate')
    op.drop_column('finance', 'budget_item')
    op.drop_column('archived_finance', 'code_rate')
    op.drop_column('archived_finance', 'budget_item')
    # ### end Alembic commands ###
