"""add_sort_order_to_equipment_files

Revision ID: df2fe060be8f
Revises: 1418f8d1f00e
Create Date: 2026-01-17 18:24:30.887967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df2fe060be8f'
down_revision: Union[str, Sequence[str], None] = '1418f8d1f00e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archived_equipment_files', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.add_column('equipment_files', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.alter_column('equipment_files', 'is_active_certificate',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment_files', 'is_active_certificate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('equipment_files', 'sort_order')
    op.drop_column('archived_equipment_files', 'sort_order')
    # ### end Alembic commands ###
