"""Add backup_history table

Revision ID: f7e0dadf8ae2
Revises: 3022ff928dd6
Create Date: 2025-10-18 08:47:44.451597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e0dadf8ae2'
down_revision: Union[str, Sequence[str], None] = '3022ff928dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='backup_status_enum'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_history'))
    )
    op.create_index(op.f('ix_backup_history_id'), 'backup_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backup_history_id'), table_name='backup_history')
    op.drop_table('backup_history')
    # ### end Alembic commands ###
